version: '3.8'

services:

  registry-php-composer:
    # restart: always
    image: registry:3.0.0-alpha.1
    ports:
      - 5000:5000
    container_name: registry-php-composer
    
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.local.crt
      REGISTRY_HTTP_TLS_KEY: /certs/registry.local.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - type: bind
        source: ./data-registrymy
        target: /var/lib/registry
        bind:
          propagation: rshared
      - type: bind
        source: ./security-settings/certs
        target: /certs
      - type: bind
        source: ./security-settings/auth
        target: /auth
